"""Add category department mapping table

Revision ID: 33b6cb73e9ad
Revises: abd083a4516f
Create Date: 2025-10-05 19:50:11.845975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b6cb73e9ad'
down_revision: Union[str, Sequence[str], None] = 'abd083a4516f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_department_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'subcategory', name='unique_category_subcategory')
    )
    op.create_index('idx_category_subcategory', 'category_department_mappings', ['category', 'subcategory'], unique=False)
    op.create_index(op.f('ix_category_department_mappings_category'), 'category_department_mappings', ['category'], unique=False)
    op.create_index(op.f('ix_category_department_mappings_id'), 'category_department_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_category_department_mappings_subcategory'), 'category_department_mappings', ['subcategory'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_department_mappings_subcategory'), table_name='category_department_mappings')
    op.drop_index(op.f('ix_category_department_mappings_id'), table_name='category_department_mappings')
    op.drop_index(op.f('ix_category_department_mappings_category'), table_name='category_department_mappings')
    op.drop_index('idx_category_subcategory', table_name='category_department_mappings')
    op.drop_table('category_department_mappings')
    # ### end Alembic commands ###
