"""update auth models for new endpoints

Revision ID: b2a3af3cf86b
Revises: 7401b20fac54
Create Date: 2025-10-02 12:04:01.784371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a3af3cf86b'
down_revision: Union[str, Sequence[str], None] = '7401b20fac54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Handle otp_verifications table changes
    op.drop_constraint('otp_verifications_pkey', 'otp_verifications', type_='primary')
    op.add_column('otp_verifications', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('otp_verifications', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('otp_verifications', sa.Column('retry_after', sa.TIMESTAMP(), nullable=True))
    
    # Create sequence and set default values for id
    op.execute("CREATE SEQUENCE otp_verifications_id_seq")
    op.execute("UPDATE otp_verifications SET id = nextval('otp_verifications_id_seq')")
    op.alter_column('otp_verifications', 'id', nullable=False)
    op.execute("ALTER SEQUENCE otp_verifications_id_seq OWNED BY otp_verifications.id")
    
    op.alter_column('otp_verifications', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.create_primary_key('otp_verifications_pkey', 'otp_verifications', ['id'])
    op.create_index(op.f('ix_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    
    # Handle user_tokens table changes
    op.add_column('user_tokens', sa.Column('access_token', sa.String(length=500), nullable=False, server_default=''))
    op.add_column('user_tokens', sa.Column('refresh_token', sa.String(length=500), nullable=True))
    op.add_column('user_tokens', sa.Column('token_type', sa.String(length=20), nullable=True, server_default='bearer'))
    op.add_column('user_tokens', sa.Column('refresh_expires_at', sa.TIMESTAMP(), nullable=True))
    op.execute("UPDATE user_tokens SET access_token = token WHERE access_token = ''")
    op.alter_column('user_tokens', 'access_token', server_default=None)
    op.alter_column('user_tokens', 'token_type', server_default=None)
    op.drop_column('user_tokens', 'token')
    
    # Handle users table changes
    op.add_column('users', sa.Column('id', sa.String(length=36), nullable=False, server_default=''))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_profile_complete', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    
    # Generate UUIDs for existing users
    op.execute("UPDATE users SET id = gen_random_uuid()::text WHERE id = ''")
    op.execute("UPDATE users SET full_name = name WHERE name IS NOT NULL")
    op.execute("UPDATE users SET is_profile_complete = true WHERE name IS NOT NULL")
    
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'id', server_default=None)
    op.alter_column('users', 'is_profile_complete', server_default=None)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_profile_complete')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'email')
    op.drop_column('users', 'id')
    
    op.add_column('user_tokens', sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False, server_default=''))
    op.execute("UPDATE user_tokens SET token = access_token WHERE token = ''")
    op.alter_column('user_tokens', 'token', server_default=None)
    op.drop_column('user_tokens', 'refresh_expires_at')
    op.drop_column('user_tokens', 'token_type')
    op.drop_column('user_tokens', 'refresh_token')
    op.drop_column('user_tokens', 'access_token')
    
    op.drop_index(op.f('ix_otp_verifications_id'), table_name='otp_verifications')
    op.drop_constraint('otp_verifications_pkey', 'otp_verifications', type_='primary')
    op.alter_column('otp_verifications', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_column('otp_verifications', 'retry_after')
    op.drop_column('otp_verifications', 'email')
    op.drop_column('otp_verifications', 'id')
    op.create_primary_key('otp_verifications_pkey', 'otp_verifications', ['phone_number'])
    # ### end Alembic commands ###
