"""add subcategory and custom_id to issues

Revision ID: be97e5d0d30e
Revises: 39769358bbda
Create Date: 2025-10-02 15:12:11.102486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be97e5d0d30e'
down_revision: Union[str, Sequence[str], None] = '39769358bbda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('custom_id', sa.String(length=50), nullable=True))
    op.add_column('issues', sa.Column('subcategory', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'issues', ['custom_id'])
    
    # Update default status from 'pending' to 'reported' for new issues
    op.execute("ALTER TABLE issues ALTER COLUMN status SET DEFAULT 'reported'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert default status back to 'pending'
    op.execute("ALTER TABLE issues ALTER COLUMN status SET DEFAULT 'pending'")
    
    op.drop_constraint(None, 'issues', type_='unique')
    op.drop_column('issues', 'subcategory')
    op.drop_column('issues', 'custom_id')
    # ### end Alembic commands ###
